apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 300m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
