apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: default
---
# Role w/o access to a cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dave
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-rb
roleRef:
  kind: Role
  name: dave
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: dave
    namespace: default
