ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.34.89.7.206.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.89.7.206.nio.io-tls
env:
  open:
    DISABLE_API: false
    STORAGE: google
    STORAGE_GOOGLE_BUCKET: chartmuseum-otus-bucket
    STORAGE_GOOGLE_PREFIX: stage
gcp:
  secret:
    enabled: true
    name: chartmuseum-gcs-secret
    key: credentials.json
