repositories:
  - name: harbor
    url: https://helm.goharbor.io
releases:
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    wait: true
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args:
          - "-c"
          - >-
            kubectl get namespace "{{`{{ .Release.Namespace }}`}}" >/dev/null 2>&1 || kubectl create namespace "{{`{{ .Release.Namespace }}`}}";
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args:
          - "-c"
          - >-
            export INGRESS_IP=$(kubectl -n nginx-ingress get services nginx-ingress-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}");
            echo "Ingress IP: $INGRESS_IP";
    values:
      - expose:
          tls:
            enabled: true
          ingress:
            hosts:
              core: harbor.34.89.102.97.nip.io
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
      - notary:
          enabled: false
