---
kind: Namespace
apiVersion: v1
metadata:
  name: app
---
kind: Service
apiVersion: v1
metadata:
  namespace: app
  name: nginx-service
  labels:
    tier: frontend
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        version: 1.19.0
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
  selector:
    matchLabels:
      app: nginx
