apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nginx
  name: nginx-servicemonitor
  namespace: app
spec:
  endpoints:
    - interval: 5s
      port: web
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: nginx
