apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  initContainers:
    - name: web-init-container
      image: busybox:latest
      command: [
        'sh',
        '-c',
        'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh; chmod -R a=r /app/*'
      ]
      volumeMounts:
        - name: app
          mountPath: /app
  containers:
    - name: web-server-hw-1
      image: ifqthenp/server-hw-1:latest
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
      livenessProbe:
        tcpSocket:
          port: 8000
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
